services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    networks:
      - app-network
  app:
    image: gtg-express
    ports:
      - 8000:8080
    depends_on:
      - postgres
    networks:
      - app-network
networks:
  app-network:
    driver: bridge