version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DATABASE: ${DB_DATABASE}
  app:
    image: gtg-express
    port:
      - 13000:8080